### ISSUE TITLE
A `checkout` action similar to `actions/checkout`

### ISSUE THREAD

**Issue by Byron** [Byron/gitoxide#1238]
### Summary 💡

The `gix`-powered checkout action should be serving as drop-in for the default usage of [`actions/checkout`](https://github.com/actions/checkout), so people are able to simply replace `actions/` with `owner-or-organization` to benefit from the increased performance and efficiency that `gix` provides.

### Thoughts

* When an MVP is ready and it's genuinely useful already, the repository could be moved into an official location.
* The MVP should be supporting the most basic usage of `actions/checkout` that most people are using. Parameters are secondary, but unsupported ones should already trigger failure stating that it's not implemented, if it's not implemented.

### Motivation 🔦

Leverage the superior cloning and checkout performance of `gix` to make CI a little faster, probably while heating the data-center less.

**Comment by mbodmer** [comment]
I would even prefer not replicating the official action with javascript just using gix, but let gix gain the functionality of such an action. Maybe provide a seperate action.yml, but this wouldn't really be needed. I imagine something along the lines of:

```yml
container:
  image: rust:alpine
steps:
  - name: install APK dependencies
    run: apk add --no-cache gitoxide
  - name: checkout
    run: gix github-action <optional input params here>
```

Of course it would be possible to do this with multiple gix commands manually.

The checkout action however does multiple things like evaluating GITHUB_* environment variables and following it's process of creating user settings and shallow checkout to fallback logic from local to remote... This is what gix could replicate.

So finally I can only install gix, then use it like an action, minus all the actions dependencies I would possibly not want.

This way a gitoxide action would also offer special functionality not offered by the official github action. This action can be used in containers without nodejs, or on alternative runners like forgejo which also provide a mostly github compatible environment.

**Comment by Byron** [comment]
I like this approach, as in addition to everything @mbodmer mentioned, it's also easier for us to implement and maintain.

Besides that I may add that with the arrival of hardened SHA1, the performance benefits are greatly reduced, making the version without hardened SHA1 2.4x faster.

With the advent of SHA256 that should go back to normal though.

**Comment by mbodmer** [comment]
Thank you for your feedback @Byron. Sorry for hijacking the issue, but let me explore the requirements we could possibly have:

- A new subcommand "ci-action" (gix or ein?)
- Read Github Action Environment (ENV):
  - Recognize runner (Github, Forgejo, nektos/Act, Others?) and adapt defaults and maybe behaviour where needed
  - Inputs of the actions will become optional commandline args with defaults based on the environment.
  - If possible no required parameters should be needed (minimize user load, context is well defined)
- sub-subcommands
  - "checkout": Implements the [actions/checkout](https://github.com/actions/checkout) behaviour. This seems where implementation should start.
  - "gitconfig": Implements the [OleksiyRudenko/gha-git-credentials](https://github.com/OleksiyRudenko/gha-git-credentials) behaviour. This is possibly something which the checkout action also does under the hood, so bring it to the user surface. It is helpful in contexts like e.g: [release-plz](https://github.com/release-plz/action) which modifies the checked out code and needs to push the modified branch.
  - "autopush": checkout a branch, execute a command which is passed as input, if successful and modified code, commit and push. Similar to: [dependencies-autoupdate](https://github.com/romoh/dependencies-autoupdate). Useful for e.g. cargo update, clippy --fix, rustfmt and automatically push to a branch. Can gitoxide also create PRs? Probably not.
  - I could imagine other helpful subcommands, but this does probably not need to be discussed for now

I am really thinking on jumping in on that, as I think this would be really great to have. But I am not sure yet what a good approach could be here. I don't really know the gitoxide codebase and didn't use gix/ein a lot yet.

There is probably a highlevel part (parsing the environment into defaults, determining the runner, parsing the options) and a low level part implementing the actual behaviour as simple functions.

Any comments?

Some links:
- Github
  - [Github Actions Doc](https://docs.github.com/en/actions?ref=faun)
  - [Github Env](https://docs.github.com/en/enterprise-cloud@latest/actions/reference/workflows-and-actions/variables)
- Gitea
  - [Gitea Runner](https://about.gitea.com/products/runner/)
- Forgejo
  - [Forgejo Runner](https://code.forgejo.org/forgejo/runner)
  - [Forgejo Env](https://forgejo.org/docs/v12.0/user/actions/reference/#env-1)
  - [Forgejo Repo Token](https://forgejo.org/docs/v1.21/user/actions/#automatic-token)
- nektos/act (Gitea, Forgejo are based on act)
  - [nektos/act](https://github.com/nektos/act)
- Crates
  - [github-actions](https://crates.io/crates/github-actions)
  - [github-action-runner](https://crates.io/crates/github-action-runner)
  - [action-rs](https://github.com/romnn/action-rs)
  - [gh-actions](https://crates.io/crates/gh_actions)
  - WASM
    - [ferrous-action](https://crates.io/crates/ferrous-actions) Very interesting concept with action.yml in repo root and wasm compiled action. Seems not ready, unfortunately.
    - [rust-wasm-action](https://github.com/peter-evans/rust-wasm-action)

**Comment by mbodmer** [comment]
After what I have learnt until now, I would suggest the following design for gitoxide actions:

One seperate GitoxideLabs/actions repository containing action.yaml files in subdirectories for each action. I would change my prior proposal to use [docker actions](https://docs.github.com/de/actions/tutorials/use-containerized-services/create-a-docker-container-action?learn=create_actions&learnProduct=actions) instead. So an action.yml would look something like:

```yml
name: 'gitoxide checkout'
description: 'actions/checkout using gitoxide'
inputs:
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
# ... more inputs, can be taken from the original action: https://github.com/actions/checkout/blob/main/action.yml
outputs:
  ref:
    description: 'The branch, tag or SHA that was checked out'
  commit:
    description: 'The commit SHA that was checked out'
runs:
  using: 'docker'
  image: 'Dockerfile' # or maybe better referencing an image for optimization
  entrypoint: gix checkout
```

Instead of each action containing its dockerfile. they all can reference the same container image. The action repo would also contain its own workflow to build that image. Preferably an alpine container with gitoxide preinstalled. As small as possible. This will allow for caching and minimizes downloads during action execution. Alternatively the image could be built in the main gitoxide repo. I am not sure yet how the image could be different depending on the architecture. Multiarch maybe?

This way a gitoxide action could be made a drop-in replacement for actions/checkout.

The gitoxide code would parse INPUT_xyz for the inputs and write GITLAB_OUTPUT, depending on the runner.
